name: Deploy Test Reports to Vercel

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allow manual trigger

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run linting
        run: yarn lint
        
      - name: Run type checking
        run: yarn type-check
        
      - name: Install Playwright browsers
        run: yarn playwright install --with-deps
        
      - name: Run Playwright tests
        run: yarn test
        env:
          CI: true
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          
      - name: Deploy to Vercel
        uses: vercel/action@v1
        if: always() # Deploy even if tests fail to show failures
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          
      - name: Comment PR with report URL
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request' && always()
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Get Vercel deployment URL from previous step
            const deploymentUrl = process.env.VERCEL_URL || 'https://spend-track-testing-reports.vercel.app';
            
            const comment = `## 🧪 Test Report
            
            The test suite has completed. You can view the detailed report here:
            
            🔗 **[View Test Report](${deploymentUrl})**
            
            ### Test Summary
            - ✅ All quality checks completed
            - 📊 Detailed results available in the report
            - 🎯 Evidence collected for analysis
            
            The report includes:
            - Test execution results
            - Screenshots and videos
            - Performance metrics
            - Error details (if any)
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
